Задание1. Получить данные из файла computer_games.csv

Задание 2. Написать функцию для поиска игры по названию (функция должна найти похожие по названию проекты и вывести их в консоль, для этого вам пригодиться метод .find() который можно вызвать у строковых полей)

Задание 3. Написать функцию для поиска игр конкретного разработчика (функция должна принимать таблицу и разработчика, а возвращать новую таблицу с играми только этого разработчика)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Задание 2. Написать функцию для поиска игры по названию (функция должна найти похожие по названию проекты и вывести их в консоль, для этого вам пригодиться метод .find() который можно вызвать у строковых полей)

In [30]:
df = pd.read_csv("computer_games.csv")
name_lower = df["Name"].str.lower()
name_lower

0                                  a-men 2
1                                  a-train
2                               a-10 cuba!
3                                a.d. 2044
4       a.d.a.m. life's greatest mysteries
                       ...
1090                  688(i) hunter/killer
1091                              7 colors
1092                                  7554
1093                            7th legion
1094                    9: the last resort
Name: Name, Length: 1095, dtype: object

In [54]:
def find_game(file_csv,name_game, search_game):
    found_indices = name_lower.str.find(search_game) != -1
    return df[found_indices]

In [55]:
result_find = find_game("computer_games.csv", 'Name', 'legend')
print(result_find)
result_find

                                                Name              Developer  \
107                                     Apex Legends  Respawn Entertainment
138                                   A Blind Legend                 Dowino
379             An Elder Scrolls Legend: Battlespire     Bethesda Softworks
401   Eye of the Beholder II: The Legend of Darkmoon    Westwood Associates
487                 Guitar Hero III: Legends of Rock              Neversoft
575                                League of Legends             Riot Games
576                              Legends of Callasia  Boomzap Entertainment
750                                   Rayman Legends                Ubisoft
775                 Rise of Nations: Rise of Legends         Big Huge Games
898                               Stronghold Legends        Firefly Studios
937                              Tomb Raider: Legend       Crystal Dynamics
1063                                     007 Legends                Eurocom

                         Producer                 Genre  \
107               Electronic Arts         Battle royale
138               Plug In Digital     Action, Adventure
379            Bethesda Softworks   Action role-playing
401   Strategic Simulations, Inc.          Fantasy, RPG
487                   Aspyr Media         Music, Rhythm
575                    Riot Games                  MOBA
576         Boomzap Entertainment   Turn-based strategy
750                       Ubisoft            Platformer
775        Microsoft Game Studios    Real-time strategy
898                      2K Games                   RTS
937             Eidos Interactive      Action-adventure
1063                   Activision  First-person shooter

                 Operating System      Date Released
107             Microsoft Windows   February 4, 2019
138      Microsoft Windows, macOS      April 7, 2016
379                        MS-DOS  November 30, 1997
401                        MS-DOS  December 12, 1991
487   Microsoft Windows, Mac OS X  November 13, 2007
575      Microsoft Windows, macOS   October 27, 2009
576      Microsoft Windows, macOS      June 10, 2016
750             Microsoft Windows  September 3, 2013
775      Microsoft Windows, macOS        May 9, 2006
898             Microsoft Windows   October 13, 2006
937             Microsoft Windows      April 7, 2006
1063            Microsoft Windows   November 2, 2012

,Name,Developer,Producer,Genre,Operating System,Date Released
107,Apex Legends,Respawn Entertainment,Electronic Arts,Battle royale,Microsoft Windows,"February 4, 2019"
138,A Blind Legend,Dowino,Plug In Digital,"Action, Adventure","Microsoft Windows, macOS","April 7, 2016"
379,An Elder Scrolls Legend: Battlespire,Bethesda Softworks,Bethesda Softworks,Action role-playing,MS-DOS,"November 30, 1997"
401,Eye of the Beholder II: The Legend of Darkmoon,Westwood Associates,"Strategic Simulations, Inc.","Fantasy, RPG",MS-DOS,"December 12, 1991"
487,Guitar Hero III: Legends of Rock,Neversoft,Aspyr Media,"Music, Rhythm","Microsoft Windows, Mac OS X","November 13, 2007"
575,League of Legends,Riot Games,Riot Games,MOBA,"Microsoft Windows, macOS","October 27, 2009"
576,Legends of Callasia,Boomzap Entertainment,Boomzap Entertainment,Turn-based strategy,"Microsoft Windows, macOS","June 10, 2016"
750,Rayman Legends,Ubisoft,Ubisoft,Platformer,Microsoft Windows,"September 3, 2013"
775,Rise of Nations: Rise of Legends,Big Huge Games,Microsoft Game Studios,Real-time strategy,"Microsoft Windows, macOS","May 9, 2006"
898,Stronghold Legends,Firefly Studios,2K Games,RTS,Microsoft Windows,"October 13, 2006"
937,Tomb Raider: Legend,Crystal Dynamics,Eidos Interactive,Action-adventure,Microsoft Windows,"April 7, 2006"
1063,007 Legends,Eurocom,Activision,First-person shooter,Microsoft Windows,"November 2, 2012"

Задание 3. Написать функцию для поиска игр конкретного разработчика (функция должна принимать таблицу и разработчика, а возвращать новую таблицу с играми только этого разработчика)

In [58]:
def find_games_ops(df: pd.DataFrame, Developer: str) -> pd.DataFrame:
    if "Developer" in df.columns:
        games_dev = df[df["Developer"] == Developer].copy()
        return games_dev
    else:
        print("Errors. Not find this info in the table")
        return pd.DataFrame()

In [66]:
dev_name = "Bethesda Softworks"
dev_games = find_games_ops(df, dev_name)
print(f"Games by {dev_name}:")
print(dev_games)
dev_games

Games by Bethesda Softworks:
                                       Name           Developer  \
372                The Elder Scrolls: Arena  Bethesda Softworks
373  The Elder Scrolls Adventures: Redguard  Bethesda Softworks
374        The Elder Scrolls II: Daggerfall  Bethesda Softworks
379    An Elder Scrolls Legend: Battlespire  Bethesda Softworks

               Producer                Genre Operating System  \
372  Bethesda Softworks  Action role-playing           MS-DOS
373  Bethesda Softworks  Action role-playing           MS-DOS
374  Bethesda Softworks  Action role-playing           MS-DOS
379  Bethesda Softworks  Action role-playing           MS-DOS

         Date Released
372     March 25, 1994
373  November 14, 1998
374    August 31, 1996
379  November 30, 1997

,Name,Developer,Producer,Genre,Operating System,Date Released
372,The Elder Scrolls: Arena,Bethesda Softworks,Bethesda Softworks,Action role-playing,MS-DOS,"March 25, 1994"
373,The Elder Scrolls Adventures: Redguard,Bethesda Softworks,Bethesda Softworks,Action role-playing,MS-DOS,"November 14, 1998"
374,The Elder Scrolls II: Daggerfall,Bethesda Softworks,Bethesda Softworks,Action role-playing,MS-DOS,"August 31, 1996"
379,An Elder Scrolls Legend: Battlespire,Bethesda Softworks,Bethesda Softworks,Action role-playing,MS-DOS,"November 30, 1997"