1. Очистить данные в представленном датасете, удалить строчки с пустыми значениями, привести данные столбца PuFrom к одному виду (имеются записи с разным регистром).

2. Перевести значение столбца Time (время поездки) во время в минутах (в таблице указаны минуты:секунды)
То есть 14:30 нужно привести к виду 14.5, а 20:15 к виду 20.25

1. Очистить данные в представленном датасете, удалить строчки с пустыми значениями, привести данные столбца PuFrom к одному виду (имеются записи с разным регистром).

In [2]:
import pandas as pd
import numpy as np

In [55]:
df = pd.read_csv("Uber.csv")

In [56]:
df["PuFrom"] = df["PuFrom"].fillna("nan")

In [57]:
df["Address"] = df["Address"].replace('      ', np.nan)

In [58]:
df["Address"] = df["Address"].fillna("nan")

In [63]:
df_clean = df.drop(index=df[df["PuFrom"] == "nan"].index)

In [61]:
df_clean = df.drop(index=df[df["Address"] == "nan"].index)

In [71]:
df_clean["PuFrom"] = df_clean["PuFrom"].astype(str)

In [74]:
df_clean["PuFrom"]= df_clean["PuFrom"].str.upper()

In [77]:
df_clean

,Date,Time,State,PuFrom,Address,Street
0,2014.07.06,14:30,NY ...,MANHATTAN,50,MURRAY ST
1,2014.07.04,7:15,NY ...,MANHATTAN,143,AVENUE B
2,2014.07.05,5:45,NY ...,MANHATTAN,125,CHRISTOPHER ST
3,2014.07.06,4:30,NY ...,MANHATTAN,217,E 7 ST
4,2014.07.05,7:45,NY ...,MANHATTAN,521,W 26 ST
...,...,...,...,...,...,...
194985,2014.09.29,9:00,NY ...,MANHATTAN,9,W 57 St
194986,2014.09.29,6:00,NJ ...,RIDGEWOOD,756,BELMONT RD
194988,2014.09.28,7:00,NY ...,MANHATTAN,112,W 78 ST
194989,2014.09.28,15:30,NY ...,MANHATTAN,601,W 57 ST
194991,2014.09.08,9:45,NY ...,MANHATTAN,415,W 24 ST



2. Перевести значение столбца Time (время поездки) во время в минутах (в таблице указаны минуты:секунды)
То есть 14:30 нужно привести к виду 14.5, а 20:15 к виду 20.25

In [78]:
def convertion(time):
  minutes, seconds = map(int, time.split(':'))
  total_minutes = minutes + seconds / 60
  return total_minutes

In [80]:
df_clean["Time"] = df_clean["Time"].apply(convertion)

In [81]:
df_clean

,Date,Time,State,PuFrom,Address,Street
0,2014.07.06,14.50,NY ...,MANHATTAN,50,MURRAY ST
1,2014.07.04,7.25,NY ...,MANHATTAN,143,AVENUE B
2,2014.07.05,5.75,NY ...,MANHATTAN,125,CHRISTOPHER ST
3,2014.07.06,4.50,NY ...,MANHATTAN,217,E 7 ST
4,2014.07.05,7.75,NY ...,MANHATTAN,521,W 26 ST
...,...,...,...,...,...,...
194985,2014.09.29,9.00,NY ...,MANHATTAN,9,W 57 St
194986,2014.09.29,6.00,NJ ...,RIDGEWOOD,756,BELMONT RD
194988,2014.09.28,7.00,NY ...,MANHATTAN,112,W 78 ST
194989,2014.09.28,15.50,NY ...,MANHATTAN,601,W 57 ST
194991,2014.09.08,9.75,NY ...,MANHATTAN,415,W 24 ST